name: Ejecutar Script Cada 15 Días

on:
  schedule:
    # Programado para correr a las 00:00 (UTC) cada 15 días
    #- cron: '0 0 */15 * *'
    - cron: '0 * * * *' #cada hora para testear

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
#    - name: Instalar dependencias
#      run: |
#        pip install random datetime
    - name: Ejecutar script
      run: python loteria.py
      
    - name: Commit files
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git pull
        git add --all
        if [-z "$(git status --porcelain)"]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Add changes" -a
           echo "::set-output name=push::true"
        fi
      shell: bash
      
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
